name: Basic Node.js CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: ./node-ci-demo

      - name: Run test cases
        run: npm test
        working-directory: ./node-ci-demo